"""rename department

Revision ID: 195b1943cd25
Revises: 8b82079a538b
Create Date: 2024-06-29 22:02:10.181427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195b1943cd25'
down_revision = '8b82079a538b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
